name: Publish release APK

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     tags:
#       - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ master ]

jobs:
  package-release-apk:
    name: Generate release APK
#     runs-on: ubuntu-latest
    runs-on: [self-hosted]
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate signed APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/core/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
        env:
          BUILD_TOOLS_VERSION: "29.0.3"

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: Simple-Dialer-withTruecaller-release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Echo APK
        run: echo Signed APK FILE ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Release signed APK
        uses: MicahSphelele/action-publish-signed-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          FILE_DIR: ${{steps.sign_app.outputs.signedReleaseFile}}
